### ISSUE TITLE
More Features

### ISSUE THREAD

**Issue by wandersonwhcr** [cyrosy/php-end-of-life#1]
Hello, @cyrosy !

Thank you for this project. This is exactly what I need to use inside workflows to check if projects sources are outdated.

Are you maintaining this project? I have some ideas, like:

* check PHP 8.0
* create a CLI to test current PHP version
* throw an warning if in security support
* throw an error if not active

Can I send you PRs with these features?

**Comment by cyrosy** [comment]
Hi !
Happy to know this bunch of code is useful :-)

I added PHP 8.0 security updates end date, but code has not been tested on PHP 8 and may need some adjustments, so i did not update the supported versions in composer.json yet.

I currently have limited extra time to maintain the project, so I would only accept PRs that don't add too much complexity or require regular updates to be meaningful.

-> a CLI tool checking if current PHP version is supported is 2 lines of code (require autoload + call the lib), this would be a great addition with minimal maintenance cost so i would accept a PR
-> throw an error if not active : I would accept a PR as well, maybe adding a second class using the current one as source of data. That would allow developers to use the one matching their needs
-> throw warning if in security support : I think adding a method in the current class that returns true if passed PHP version in security support would indeed be very useful, and a wrapper-class could use this method to add deprecated error message

So yes I guess you could send PRs with all those features, I will gladly check and merge them !

**Comment by wandersonwhcr** [comment]
OK! TY <3
